// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectAndLaunch() {
  return window['go']['main']['App']['ConnectAndLaunch']();
}

export function ConnectVPN() {
  return window['go']['main']['App']['ConnectVPN']();
}

export function DisconnectVPN() {
  return window['go']['main']['App']['DisconnectVPN']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
